name: Deploy Vite app to GitHub Pages

on:
  push:
    branches:
      - main   # ⚠️ change si ta branche principale n’est pas 'main'

permissions:
  contents: write    # ⬅️ donne le droit de créer/pousser des branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Add .nojekyll
        run: touch dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true   # ⬅️ recrée une branche gh-pages propre à chaque fois
